import type { CommercialArticleSeed } from "./types";

const ranking = "https://kakaku.com/ranking/kaden/";
const date = "2026-09-16";
const rows = (left: string, right: string) => [
  { label: "公式で確認するポイント", left, right },
  {
    label: "選び方",
    left: "仕様を公式ページで確認",
    right: "仕様を公式ページで確認",
  },
  { label: "価格・在庫", left: "販売先で確認", right: "販売先で確認" },
];
const faq = (left: string, right: string) => [
  {
    question: `${left}と${right}はどちらが安い？`,
    answer: "価格と在庫は変動するため、販売先の最新表示をご確認ください。",
  },
  {
    question: "価格.comの売れ筋をどう参考にした？",
    answer:
      "価格.com家電ランキングの2026年9月上旬集計を商品選定の参考にし、仕様の根拠は各メーカー公式情報に分けています。",
  },
];
const make = (
  id: string,
  category: string,
  brand: string,
  left: string,
  right: string,
  leftPoint: string,
  rightPoint: string,
  official: string,
): CommercialArticleSeed => ({
  id,
  publishedAt: date,
  modifiedAt: date,
  productInfoCheckedAt: date,
  purchaseLinksCheckedAt: date,
  purchaseLinkStatus: "unverified",
  title: `${brand} ${left}と${right}、どっち？｜くらべる商品メモ`,
  headline: `${brand} ${left}と${right}を比較。価格.com売れ筋を参考に選び方を整理`,
  description: `${left}と${right}を、メーカー公式情報と価格.com売れ筋ランキングを分けて確認します。`,
  category,
  tags: [category, "価格.com売れ筋", "公式仕様"],
  audiences: [
    `${category}の購入候補を比べたい人`,
    "価格.comの売れ筋から候補を探したい人",
  ],
  uses: ["購入前の比較", "仕様確認", "選び方の整理"],
  summary: `${left}と${right}について、公式ページで確認できる項目を比較し、価格.comランキングを候補選びの参考として整理します。`,
  leftProduct: left,
  rightProduct: right,
  leftPoint,
  rightPoint,
  verifiedRows: rows(leftPoint, rightPoint),
  faqEntries: faq(left, right),
  socialProofHasPosts: false,
  officialSources: [
    { label: `${brand}公式サイト`, url: official as `https://${string}` },
  ],
  sourceLinks: [
    {
      label: "価格.com 家電カテゴリランキング（2026年9月上旬集計）",
      url: ranking,
      date,
    },
  ],
});

export const kakakuSeptember2026Seeds: readonly CommercialArticleSeed[] = [
  make(
    "toshiba-tw-127xm5l-vs-panasonic-na-lx127el",
    "洗濯機",
    "東芝・パナソニック",
    "ZABOON TW-127XM5L",
    "NA-LX127EL-W",
    "洗濯容量・乾燥方式を確認",
    "洗濯容量・乾燥方式を確認",
    "https://www.toshiba-lifestyle.com/jp/laundries/",
  ),
  make(
    "airpods-pro-3-vs-sony-wf-1000xm6",
    "イヤホン・ヘッドホン",
    "Apple・SONY",
    "AirPods Pro 3 MFHP4J/A",
    "WF-1000XM6",
    "連携機能と装着感を確認",
    "ノイズキャンセリングと再生時間を確認",
    "https://www.apple.com/jp/airpods-pro/",
  ),
  make(
    "regza-32v35s-vs-regza-43m550m",
    "テレビ",
    "TVS REGZA",
    "REGZA 32V35S",
    "REGZA 43M550M",
    "設置場所に合う画面サイズを確認",
    "設置場所に合う画面サイズを確認",
    "https://www.regza.com/",
  ),
  make(
    "hitachi-pv-bl1c4-vs-dyson-sv46-ff",
    "掃除機",
    "日立・ダイソン",
    "ラクかるスティック PV-BL1C4",
    "Dyson V12 Detect Slim Fluffy SV46 FF",
    "本体の軽さと手入れ方法を確認",
    "ヘッド機能と運転時間を確認",
    "https://kadenfan.hitachi.co.jp/clean/",
  ),
  make(
    "toshiba-er-d3000b-vs-aladdin-agt-g13b",
    "電子レンジ・オーブンレンジ",
    "東芝・日本エー・アイ・シー",
    "石窯ドーム ER-D3000B",
    "Aladdin グラファイト グリル&トースター 4枚焼き",
    "庫内サイズとオーブン機能を確認",
    "トースト枚数と加熱方式を確認",
    "https://www.toshiba-lifestyle.com/jp/microwave/",
  ),
  make(
    "zojirushi-nx-ab10-vs-nw-wd10",
    "炊飯器",
    "象印",
    "炎舞炊き NX-AB10",
    "豪熱大火力 NW-WD10",
    "炊飯方式と炊き分けを確認",
    "炊飯方式と炊き分けを確認",
    "https://www.zojirushi.co.jp/syohin/ricecooker/",
  ),
  make(
    "hitachi-ras-aj2226s-vs-daikin-s406atep",
    "エアコン・クーラー",
    "日立・ダイキン",
    "白くまくん RAS-AJ2226S",
    "S406ATEP-W",
    "適用畳数と設置条件を確認",
    "適用畳数と設置条件を確認",
    "https://kadenfan.hitachi.co.jp/ra/",
  ),
  make(
    "sony-wh-1000xm6-vs-airpods-max",
    "イヤホン・ヘッドホン",
    "SONY・Apple",
    "WH-1000XM6",
    "AirPods Max",
    "ノイズキャンセリングと接続先を確認",
    "Apple製品との連携と装着感を確認",
    "https://www.sony.jp/headphone/",
  ),
  make(
    "switch-2-vs-switch-2-zelda",
    "ゲーム機本体",
    "任天堂",
    "Nintendo Switch 2 BEE-S-KB6CA",
    "Nintendo Switch 2 ゼルダの伝説 40周年 BEE-S-KL6CC",
    "本体仕様と付属品を確認",
    "本体仕様と限定同梱物を確認",
    "https://www.nintendo.com/jp/hardware/switch2/",
  ),
  make(
    "panasonic-eh-na0k-vs-panasonic-eh-na9m",
    "ヘアドライヤー",
    "パナソニック",
    "ナノケア EH-NA0K",
    "ナノケア EH-NA9M",
    "ケア機能と風量を確認",
    "ケア機能と風量を確認",
    "https://panasonic.jp/hair/",
  ),
];
