import type { CommercialArticleSeed } from "./types";

export const sonyWf1000xm6VsLinkbudsFitSeed: CommercialArticleSeed = {
  id: "sony-wf-1000xm6-vs-linkbuds-fit",
  publishedAt: "2026-09-20",
  modifiedAt: "2026-09-20",
  handoffManifestId: "sony-wf-1000xm6-vs-linkbuds-fit-2026-09-20",
  productInfoCheckedAt: "2026-09-20",
  purchaseLinksCheckedAt: "2026-09-20",
  purchaseLinkStatus: "direct",
  title: "ソニー WF-1000XM6とLinkBuds Fitの違いを比較｜重さ・電池・価格は？",
  headline: "ソニーの完全ワイヤレスイヤホンを比較。ノイキャン重視と軽さ重視の違い",
  description: "ソニー WF-1000XM6とLinkBuds Fitを、公式仕様と公開された実利用者の感想で比較します。",
  category: "イヤホン・ヘッドホン",
  tags: ["イヤホン", "ソニー", "ノイズキャンセリング"],
  audiences: ["ソニーの完全ワイヤレスイヤホンを選びたい人", "WF-1000XM6とLinkBuds Fitで迷っている人"],
  uses: ["通勤・通学", "音楽鑑賞", "オンライン通話"],
  summary: "ノイズキャンセリング時の電池持ちとワイヤレス充電ならWF-1000XM6、軽さと価格ならLinkBuds Fitが向いています。",
  lead: "結論：ノイキャン・電池・充電の便利さならWF-1000XM6、軽さと価格ならLinkBuds Fitです。",
  leftProduct: "ソニー ワイヤレスノイズキャンセリングステレオヘッドセット WF-1000XM6",
  rightProduct: "ソニー ワイヤレスノイズキャンセリングステレオヘッドセット LinkBuds Fit WF-LS910N",
  leftPoint: "NCオン8時間・ワイヤレス充電・上位機のノイキャンを重視する人向け",
  rightPoint: "片耳約4.9g・29,700円・軽い装着感を重視する人向け",
  leftImage: "/products/sony-wf-1000xm6.jpg",
  rightImage: "/products/sony-linkbuds-fit.jpg",
  leftRakutenUrl: "https://item.rakuten.co.jp/a-price/4548736171763/",
  rightRakutenUrl: "https://item.rakuten.co.jp/biccamera/4548736157873/",
  officialSources: [
    { label: "ソニー WF-1000XM6 公式商品ページ", url: "https://www.sony.jp/headphone/products/WF-1000XM6/" },
    { label: "ソニー LinkBuds Fit 公式商品ページ", url: "https://www.sony.jp/headphone/products/LinkBuds_Fit/" },
    { label: "ソニー WF-1000XM6 公式仕様", url: "https://www.sony.jp/headphone/products/WF-1000XM6/spec.html" },
    { label: "ソニー LinkBuds Fit 公式仕様", url: "https://www.sony.jp/headphone/products/LinkBuds_Fit/spec.html" },
  ],
  verifiedRows: [
    { label: "ソニーストア価格（税込）", left: "39,600円", right: "29,700円", highlight: "right", highlightNote: "9,900円安い", direction: "lower-is-better" },
    { label: "片耳重量（Mサイズ）", left: "約6.5g", right: "約4.9g", highlight: "right", highlightNote: "約1.6g軽い", direction: "lower-is-better" },
    { label: "NCオン連続再生", left: "最大8時間", right: "最大5.5時間", highlight: "left", highlightNote: "2.5時間長い", direction: "higher-is-better" },
    { label: "NCオフ連続再生", left: "最大12時間", right: "最大8時間", highlight: "left", highlightNote: "4時間長い", direction: "higher-is-better" },
    { label: "ドライバー", left: "8.4mm", right: "8.4mm", highlight: null },
    { label: "Bluetooth", left: "Ver.5.3", right: "Ver.5.3", highlight: null },
    { label: "コーデック", left: "SBC / AAC / LDAC / LC3", right: "SBC / AAC / LDAC / LC3", highlight: null },
    { label: "充電方法", left: "USB・ワイヤレス充電", right: "USB充電", highlight: "left", highlightNote: "置くだけ充電に対応" },
  ],
  faqEntries: [
    { question: "軽いのはどちら？", answer: "LinkBuds Fitです。片耳約4.9gで、WF-1000XM6の約6.5gより軽くなっています。" },
    { question: "ノイズキャンセリング時の電池持ちは？", answer: "WF-1000XM6が最大8時間、LinkBuds Fitが最大5.5時間です。長時間使うならWF-1000XM6が有利です。" },
    { question: "ワイヤレス充電できるのは？", answer: "WF-1000XM6です。ケースがワイヤレス充電に対応します。LinkBuds Fitは公式仕様でUSB充電のみです。" },
    { question: "価格を抑えたいなら？", answer: "ソニーストア価格ではLinkBuds Fitが29,700円で、WF-1000XM6より9,900円安くなっています。" },
  ],
  decisionGuideSteps: [
    "ノイズキャンセリングをオンにして長時間使うならWF-1000XM6を選ぶ",
    "片耳の軽さと価格を優先するならLinkBuds Fitを選ぶ",
    "ケースを置くだけで充電したいならWF-1000XM6を選ぶ",
    "購入前に販売ページでカラー、価格、在庫を確認する",
  ],
  officialProse: [
    { heading: "WF-1000XM6", items: ["片耳約6.5g、NCオン最大8時間、NCオフ最大12時間。", "ケースはUSB充電とワイヤレス充電に対応し、ソニーストア価格は39,600円（税込）です。"] },
    { heading: "LinkBuds Fit", items: ["片耳約4.9g、NCオン最大5.5時間、NCオフ最大8時間。", "軽さとフィット感を重視したモデルで、ソニーストア価格は29,700円（税込）です。"] },
  ],
  socialProofHasPosts: true,
  socialProofBestMatch: "model",
  socialProofCheckedAt: "2026-09-20",
  socialProofQuery: "Sony WF-1000XM6 LinkBuds Fit 使用感 レビュー",
  embeds: [
    {
      provider: "reddit",
      url: "https://www.reddit.com/r/SonyHeadphones/comments/1ta8tf2/wf1000xm6_3_months_later_the_good_the_bad_and_the/",
      title: "WF-1000XM6を3か月使った感想",
      match: "model",
      purpose: "WF-1000XM6の実利用者による長期使用の感想です。",
      tone: "mixed",
    },
    {
      provider: "reddit",
      url: "https://www.reddit.com/r/SonyHeadphones/comments/1gm8ngl/linkbuds_fit_impressions_vs_linkbuds_s/",
      title: "LinkBuds Fitの使用感",
      match: "model",
      purpose: "LinkBuds Fitを実際に使った投稿者の感想です。",
      tone: "mixed",
    },
  ],
  sourceLinks: [
    { label: "ソニー WF-1000XM6 公式商品ページ", url: "https://www.sony.jp/headphone/products/WF-1000XM6/", date: "2026-09-20" },
    { label: "ソニー WF-1000XM6 公式仕様", url: "https://www.sony.jp/headphone/products/WF-1000XM6/spec.html", date: "2026-09-20" },
    { label: "ソニー LinkBuds Fit 公式商品ページ", url: "https://www.sony.jp/headphone/products/LinkBuds_Fit/", date: "2026-09-20" },
    { label: "ソニー LinkBuds Fit 公式仕様", url: "https://www.sony.jp/headphone/products/LinkBuds_Fit/spec.html", date: "2026-09-20" },
    { label: "楽天市場 XPRICE WF-1000XM6", url: "https://item.rakuten.co.jp/a-price/4548736171763/", date: "2026-09-20" },
    { label: "楽天市場 楽天ビック LinkBuds Fit", url: "https://item.rakuten.co.jp/biccamera/4548736157873/", date: "2026-09-20" },
    { label: "Reddit・WF-1000XM6実利用投稿", url: "https://www.reddit.com/r/SonyHeadphones/comments/1ta8tf2/wf1000xm6_3_months_later_the_good_the_bad_and_the/", date: "2026-09-20" },
    { label: "Reddit・LinkBuds Fit実利用投稿", url: "https://www.reddit.com/r/SonyHeadphones/comments/1gm8ngl/linkbuds_fit_impressions_vs_linkbuds_s/", date: "2026-09-20" },
    { label: "note・LinkBuds Fit実利用記事", url: "https://note.com/pecora_n/n/ncbca2bef8e66", date: "2026-09-20" },
  ],
  disclaimer: "仕様・価格・在庫は変更される可能性があります。購入前に公式ページと販売ページをご確認ください。口コミは個人の感想です。",
};
